Fix tl.constexpr annotation form in global variables (#430)
Summary:
Follow-up for https://github.com/meta-pytorch/MSLK/pull/414, https://github.com/meta-pytorch/MSLK/pull/421 and https://github.com/meta-pytorch/MSLK/pull/425. `tl.constexpr` annotation form global variables usage in triton kernels causes compilation errors:

```bash
NameError("Cannot access global variable BF16_MIN_NORMAL from within jit'ed function. Triton kernels can only access global variables that are instanstiated as constexpr (`x = triton.language.constexpr(42)`). Note that this is different from annotating a variable as constexpr (`x: triton.language.constexpr = 42`), which is not supported.  Alternatively, set the envvar TRITON_ALLOW_NON_CONSTEXPR_GLOBALS=1, but we do not promise to support this forever.")
```


Reviewed By: q10

Differential Revision: D111238963

Pulled By: cthi